### ISSUE TITLE
Component styles doesn't work if there is more than one div inside template

### ISSUE THREAD

**Issue by futurfuturfuturfutur** [vue-styleguidist/vue-live#105]
I am using Preview component with Vue 3. And if I pass this code, there is no styles applied.
```
<template>
  <div class="test">Test</div>
  <div class="test2">Test2</div>

</template>

<script setup></script>

<style>
.test {
  width: 100px;
  height: 100px;
  background: red;
}
.test2 {
  width: 50px;
  height: 50px;
  background: green;
}
</style>
```
What I am getting as a result:
![image](https://user-images.githubusercontent.com/81389337/235856186-500ce4d7-1e40-4966-ac00-ca68a55292a6.png)
Tried this code also on demo page http://vue-live.surge.sh/, same result:
![image](https://user-images.githubusercontent.com/81389337/235856458-39c03ce4-de7c-4d62-94e5-8e2d205eaa04.png)

And what is interesting, if there is only one div inside template, it works:
![image](https://user-images.githubusercontent.com/81389337/235856641-34f27dd4-6a2f-43ba-a043-3e183356e13f.png)
![image](https://user-images.githubusercontent.com/81389337/235856697-ffb358ad-5abc-4025-952d-c4eeab874ec0.png)

As I can see after compile there is no scope data attribute applied to dives if there is more than one div inside template
Two dives:
![image](https://user-images.githubusercontent.com/81389337/235857098-411042d2-bfb9-45bd-a69b-863485f1b984.png)
One div:
![image](https://user-images.githubusercontent.com/81389337/235857386-09b30b67-f3dd-4a2c-a055-45f8fdd2100d.png)

**Comment by elevatebart** [comment]
Wooopsies... this specific case seems to be a hiccup in vue.

If you paste the code here in [the repl](https://play.vuejs.org/#__DEV__eNptj0EOgjAQRa8y6QEASdxgIfEOLtnUdgKNWJp2QA3h7raCBo2r9r/5eZmZ2NHaZByQFYx76bQl8EiDrWoje+MJBJSQ14anyzTwEAivthOEIQFwpUeQnfC+rBmhp5pVp/DwNAz+N/K1kr87PN0oQ/T06OI3iW2YouSmFbUF7LLM3g8RtKiblrbkLOSlcf1gVAEOVWDzqsi/HPtfxQdsDY1DNIsjXP9aiM1P12Fo0Q==) the code is not styled either. I wonder why that is.

**Comment by futurfuturfuturfutur** [comment]
Can I help you somehow to fix it?

**Comment by elevatebart** [comment]
Thank you @futurfuturfuturfutur 
I believe I have it sorted out. need to update a dependency
