### ISSUE TITLE
Vuepress code block loses styling on load

### ISSUE THREAD

**Issue by travispamaral** [vue-styleguidist/vue-live#20]
If I have a regular code block on the same page as a live block, the styling gets removed when live renders. Any idea why this happens? Does live have to import styles if vuepress already uses prism?

Thanks! Again great plugin :) Happy to help submit a fix if you have any ideas!

**Example of code:**
![image](https://user-images.githubusercontent.com/5941111/61148645-166f0380-a494-11e9-9d4e-dbd50be7d58d.png)

**Result:**
![Jul-12-2019 10-55-14](https://user-images.githubusercontent.com/5941111/61148415-93e64400-a493-11e9-9748-5ba59bde9773.gif)

**Comment by elevatebart** [comment]
I believe this is an issue with [vue-prism-editor](https://github.com/koca/vue-prism-editor) and the fact that it uses `v-html` to enter the prism code. I need to understand how the second time the component is rendered, it loses its language.

**Comment by travispamaral** [comment]
Ahh interesting, ok happy to help with a fix if you're able to identify. I know you all are busy! 😄

**Comment by travispamaral** [comment]
Any progress here? No rush just curious if anything has been identified. Thanks!

**Comment by elevatebart** [comment]
Have posted an issue here: https://github.com/koca/vue-prism-editor/issues/30
The demo site has the exact same issue.

**Comment by travispamaral** [comment]
Awesome thanks, I'll follow!
