### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by ManUtopiK** [vue-styleguidist/vue-live#25]
I'm trying to use your component in nuxt.js, but it throw this error:
`Failed to mount component: template or render function not defined.`
Here is the code:
```vue
<template>
  <div>
    <no-ssr>
      <vue-live :code="`<input type='button' value='button' />`" />
    </no-ssr>
  </div>
</template>
<script>
import VueLive from 'vue-live'
export default {
  components: {
    VueLive
  }
}
</script>
```
Any idea?

**Comment by elevatebart** [comment]
Hello @ManUtopiK I never tried the component using nuxt. 
Would you mind setting up a reproduction repo that I could clone ?
Thank you in advance

**Comment by ManUtopiK** [comment]
Thanks for your quick reply!
I just build a fresh new nuxt instance with only vue-live.
https://github.com/ManUtopiK/nuxt-vue-live
Build it and take a look on devtools console.

**Comment by elevatebart** [comment]
## Idea 1: use the named import for VueLive 

It is the exported component.

```js
import { VueLive } from 'vue-live'
export default {
  components: {
    VueLive
  }
}
```

But this is not enough, you need to force Nuxt to use the version of vue that embeds the compiler.

## Idea 2: Add the proper WebPack alias

It avoids the `You are using the runtime-only build of Vue where the template compiler is not available.` error.

**Comment by ManUtopiK** [comment]
It's almost that! All errors are gone, but there is something strange :
![image](https://user-images.githubusercontent.com/188172/73790837-72d3a080-47a1-11ea-8241-946e24ac277e.png)
I also used orginal Logo component. Same bug happens :/
I just pushed changes here https://github.com/ManUtopiK/nuxt-vue-live

**Comment by ManUtopiK** [comment]
> But this is not enough, you need to force Nuxt to use the version of vue that embeds the compiler.

Do you mean the main Nuxt instance doesn't use the original compiler no more, but use the embed version instead? Or Nuxt only use the embed versoin only to render vue-live content? Could it have any consequences on nuxt SSR or front? 

Although I suspected it but it does not work in SSR if we remove `<no-ssr>`. It's throw the well know error `[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content.`.
So it's not so good for SEO. It doesn't matter for now...

**Comment by elevatebart** [comment]
it feels like you are missing only CSS.
Let me check that.

**Comment by elevatebart** [comment]
A one liner will give you prism styles: 

```js
import 'prismjs/themes/prism-tomorrow.css'
```

the rest is due to using flex in the container.

**Comment by elevatebart** [comment]
I hope this helps ;-)

**Comment by elevatebart** [comment]
Here is what I get and the code for `index.vue`

![screenshot 1](https://user-images.githubusercontent.com/5592465/73795050-528aee00-476f-11ea-8491-fe0c2a1aea56.png)

```vue
<template>
  <div class="container">
    <div class="middlebox">
      <h1>Vue-live test</h1>
      <no-ssr>
        <vue-live
          :code="'<span>test</span>'"
          :components="registeredComponents"
        />
      </no-ssr>
    </div>
  </div>
</template>
<style>
.container {
  margin: 0 auto;
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  text-align: center;
}

.middlebox {
  width: 800px;
}

.title {
  font-family: 'Quicksand', 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
    'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  display: block;
  font-weight: 300;
  font-size: 100px;
  color: #35495e;
  letter-spacing: 1px;
}

.subtitle {
  font-weight: 300;
  font-size: 42px;
  color: #526488;
  word-spacing: 5px;
  padding-bottom: 15px;
}

.links {
  padding-top: 15px;
}
</style>
```

**Comment by ManUtopiK** [comment]
Oups... 🙄 
Your component is awesome!
Thanks a lot for your reactivity!

**Comment by ManUtopiK** [comment]
Now I wondering how to do server side rendering, if you have an idea?

**Comment by elevatebart** [comment]
I believe the problem is that I use `beforeMount` lifecycle hook.
[the docs](https://ssr.vuejs.org/guide/universal.html#component-lifecycle-hooks)
I replaced i with `created` which should be better. 
Can you test v1.5.0?

**Comment by elevatebart** [comment]
Yes, I missed the exact same issue in the Preview component...
Sry. will deliver in v1.5.1

**Comment by ManUtopiK** [comment]
No sorry, but this issue stay the same. Preview is not rendered in first render :/

**Comment by elevatebart** [comment]
Hello @ManUtopiK on my end I did see the pre-rendering happening.
Let me try it again.

**Comment by elevatebart** [comment]
Would you mind joining me on [VueLand](https://chat.vuejs.org) to try to figure out this mystery together?
Since we both are french it might even be easier to talk in french there. Less "lost in translation" ;)

**Comment by elevatebart** [comment]
I did try it again and created [PR#1](https://github.com/ManUtopiK/nuxt-vue-live/pull/1) to show what I mean.
It still works.

**Comment by ManUtopiK** [comment]
Oh! I'm so sorry, I updated plugin via npm but completely forgot to remove `<no-ssr>` component!
It's work 🎉 
Thanks a lot for all!
