### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by justin-schroeder** [vue-styleguidist/vue-live#26]
First — killer project 👍 Literally just magic to me.

So, I'm fully aware this is probably an insane request, ha, but is there any chance IE11 support is something you would consider shooting for? Or at least some kind of graceful degradation?

Currently if `vue-live` is on a page and you open it with IE11 it pretty much borks the site due to JS errors, the demo site http://vue-live.surge.sh:

![Screen Shot 2020-03-20 at 4 12 06 PM](https://user-images.githubusercontent.com/1950463/77203031-e289ba80-6ac5-11ea-917b-5bea1601e869.png)

**Comment by elevatebart** [comment]
this is a great idea, I should use the "modern" setting of the vue cli. Would you be interrested in creating a PR? I would help you along the way of course. 

I yes, ping me on [discord](https://chat.vuejs.org) and we can chat. I can guide you there.

**Comment by elevatebart** [comment]
Would you mind testing now? I do not have a machine yet with IE on it.

**Comment by elevatebart** [comment]
should be good now
