### ISSUE TITLE
Vue components without <script> tags?

### ISSUE THREAD

**Issue by trusktr** [vue-styleguidist/vue-live#27]
Just curious, I see some examples look like single-file components, but they don't have `<script>` tags, just JS code floating above markup.

For example:

```vue
let show = true
let today = new Date();

<input type="checkbox" v-model="show">
<date-picker 
  style="text-align:center;" 
  v-if="show" 
  :value="today"/>
```

What format is this? Is there a Vue option to not use script tags? Or are you doing something special just for this editor?

**Comment by elevatebart** [comment]
This format is a bit funky and does not work as expected all the time.
It started as a way to only display a template but... one quickly needed a few variables and BIM we ended with a 3rd norm.

The way it works:
1. Is it an SFC? using the vue-template-compiler this is super easy to determine.
1. Is it a pure JS/JSX component? we want to recognize one of the following patterns. `module.exports = {}`, `export default {}` or `new Vue({})`.
1. Else it looks for the first `<` at the beginning of a line and assumes it to be the start of the template. Each variable defined in the script part (before the template) is available as a data in the template.

I hope it clarifies a little.

**Comment by trusktr** [comment]
Interesting, thanks!
