### ISSUE TITLE
Dummy-ify the demo page

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vue-styleguidist/vue-live#30]
I went to your live demo SIX times before I found out that you can actually edit the code on the page.

That's sort of the whole point, and it is very easily missed. I then had to tell other people "oh you can actually edit it live on the page.... oh I guess that explains the name".

I think this needs a.... **New Design!**

* * *

One example, of a very simple, basic component.

GIANT text saying "YOU CAN EDIT THIS" with an arrow pointing to the code.

Then a "More examples" link, which takes you to the current demo page.

* * *

The current examples are great. I've gone through every example and all lines of code to see what's happening, I really like what you've done. But I'm afraid most will see this as a list of "stuff it can do" without realizing the main point that you can edit it live. So slimming all theses other cases down just to one thing to sell the main idea first is crucial, so *then* people can be like "yeah, but can it do X?" and go to the "More examples" page.

**Comment by elevatebart** [comment]
absolutely agree, sorry for the confusion

**Comment by elevatebart** [comment]
Hey @TheJaredWilcurt what do you this of this?

http://vue-live.surge.sh/

**Comment by TheJaredWilcurt** [comment]
PERFECTO!
