### ISSUE TITLE
[Bug]: v1.9.X template compilation error bugs in docs

### ISSUE THREAD

**Issue by codebender828** [vue-styleguidist/vue-live#36]
I went to the docs to check out the v.1.9.0 docs for the Error handling and I noticed the template compler is throwing errors in the docs even for components that not to have any syntax/dependency errors

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/21237954/81288247-d8804300-9096-11ea-82e0-8bb752902dc1.png">

**Comment by elevatebart** [comment]
uh oh !! went a little fast I guess

**Comment by elevatebart** [comment]
I'm on it. Fixed in 90 minuntes max.
Really sorry about that, I should have more integration tests.

**Comment by codebender828** [comment]
Thanks for the fix!
