### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by storageddd** [vue-styleguidist/vue-live#43]
Hello!
When I try to use vue-live with NuxtJS, I have a lot of syntax errors in IE11.

I solved this problem by adding next libraries to transpile section of NuxtJS config:
/vue-live\\/dist/,
'prismjs',
/vue-runtime-helpers/,
/vue-inbrowser-compiler/,
/acorn/,
/arocn-jsx/,
/regexpu-core/,
'unicode-match-property-ecmascript',
'unicode-match-property-value-ecmascript'

However, I think this is not good solution and need to add IE11 support and transpiling to vue-live.

_Now I use NuxtJS 2.9.1._

**Comment by elevatebart** [comment]
Thank you @storageddd, does this mean that you found a way to solve your issue?

Would you be interested in helping to add this to the docs?

**Comment by storageddd** [comment]
@elevatebart, yes I found solution. I was changed my first message.
I can add it to docs, but I think need fix it in vue-live.

**Comment by elevatebart** [comment]
I do not think this issue can be "fixed" in the vue-live package. 
A lot of the dependencies you mention above are outside of the scope of vue-live. 

To avoid duplicating the weight of dependencies, a published npm package never contains the dependencies. 
If a package chooses not to support IE11, to allow for better tree shaking for example, they can do so.
If this is the case, it is the role of the final package to transpile them into IE compatible code.

Your approach of using transpile dependencies to nuxt.config is the right one.
Your issue will already help people googling vue-live + ie11.
So thank you already.

But changing the code vue-live will not help transpiling its dependencies.

Does it make sense?

**Comment by storageddd** [comment]
@elevatebart, well, I think you are right. And It doesn`t make sense. 
Thank you for good explanation! I hope my solution will be useful. :)
