### ISSUE TITLE
 It would be better if the editor added hints

### ISSUE THREAD

**Issue by 869123771** [vue-styleguidist/vue-live#52]

**Comment by elevatebart** [comment]
Great idea,
I got parsing errors working, still need to figure out running errors.

**Comment by 869123771** [comment]
I mean, it's better to add code snippets to the code editor

**Comment by elevatebart** [comment]
What do you mean? 
Implementing autocomplete?

Code intellisense is a little heavy on the processor and bundle size for a website. 
I think, that if you are looking for these features, an instance of CodeSandbox might be more appropriate.
