### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by elevatebart** [vue-styleguidist/vue-live#54]
Vue 3 works on the next branch and the next channel
Still need to work on making some heavy refactoring.

**Comment by calebeaires** [comment]
Hi. I have tried to run the next  (Vue 3) version. 

Getting message like 

```bash
* vue in ./node_modules/element-plus/lib/index.esm.js, ./node_modules/vue-class-component/dist/vue-class-component.esm-bundler.js and 18 others

To install it, you can run: npm install --save vue

```

**Comment by botteroxom** [comment]
Mine works in dev, but not on build...

**Comment by elevatebart** [comment]
@botteroxom did you try again with newer versions? did it fail too?

If it does fail, could you open another issue please?
