### ISSUE TITLE
When using Vue CLI and Vue 3, error break the app

### ISSUE THREAD

**Issue by calebeaires** [vue-styleguidist/vue-live#57]
Default Vue 3 from Vue CLI

```
prismeditor.esm.js?e57a:36 Uncaught TypeError: Cannot read property 'extend' of undefined
    at Module.eval (prismeditor.esm.js?e57a:36)
    at eval (prismeditor.esm.js:573)
    at Module../node_modules/vue-prism-editor/dist/prismeditor.esm.js (chunk-vendors.js:7180)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at Module.eval (vue-live.esm.js?9838:1)
    at eval (vue-live.esm.js:1178)
    at Module../node_modules/vue-live/lib/vue-live.esm.js (chunk-vendors.js:7156)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
```

**Comment by elevatebart** [comment]
It might have to do with the fixes added on vue-prism-editor.
Let me check this.

**Comment by elevatebart** [comment]
What version are you using?

Vue 3 is only working with the alpha version.

To install the alpha version for vue3 run the following command.

```sh
npm install vue-live@next
```

**Comment by elevatebart** [comment]
Oh !!! Vite's integration is going to be a tough cookie.

Vite natural aliases don't allow to shim what is returned by `import { vue } from 'vue'` which is what is necessary for vue-live to work. 
https://github.com/vitejs/vite/issues/279

We would need to create a new resolver to short circuit this resolving of `vue` like in vuepress.
https://github.com/vuejs/vitepress/blob/master/src/node/resolver.ts#L19

**Comment by elevatebart** [comment]
Actually, scratch that, let me try and use this alias thing in vite.
According to the docs, one can even do is here.

https://github.com/vitejs/vite/blob/master/src/node/config.ts#L93

Talk to you as soon as I have an example.

**Comment by elevatebart** [comment]
I found another issue, fixing...

**Comment by elevatebart** [comment]
Sounds like my initial fear was actually founded. 
When adding the needed alias, I get the following error

```
[vite] Failed to resolve module import "dist/vue.runtime.esm-browser.js". (imported by /src/App.vue)
```

even though the file actually exists, it is simply ignored by vite. I wonder why.

**Comment by elevatebart** [comment]
check out this repo https://github.com/elevatebart/vite-live

**Comment by calebeaires** [comment]
Hey @elevatebart , I take a look at you vite-live. 

@yyx990803 Evan You are making some changes to Vite/Vue3. Maybe we are going to find out that Vite and vue-live can finally have a match!

Closing this issue! Thanks. 🙏
