### ISSUE TITLE
Next: Invalid attribute name: data-test, aria-labelledby

### ISSUE THREAD

**Issue by LeBenLeBen** [vue-styleguidist/vue-live#59]
I’ve just updated to version `2.0.0-alpha.3` and I get errors on some attributes that shouldn’t probably throw.

> [VueLive] Invalid attribute name: data-test
> [VueLive] Invalid attribute name: aria-labelledby

When this happens, the code block display is weird as well, an element with the class `VueLive-squiggles-wrapper" seems to be creating some weird white space within the Prism editor.

![Screenshot_2020-11-13 Chūshō Playground](https://user-images.githubusercontent.com/793344/99088508-6e5bd400-25cc-11eb-817e-3b34ddb79ceb.png)

**Comment by LeBenLeBen** [comment]
This line seems to be the issue: https://github.com/vue-styleguidist/vue-live/blob/next/src/utils/checkTemplate.js#L52

The regex looks odd to me, especially the `,-,` part since it means, I think, all characters between `,` and `,` which doesn’t really make sense?!

I’m not sure which characters are allowed in attributes but I guess `,` isn’t one of them whereas `-` is. I’d propose to adapt it to something like `/^[a-z\-:]+$/g`

WDYT?

**Comment by elevatebart** [comment]
Thank you so much @LeBenLeBen ,

You were absolutely right. I added a couple of additional tests just so things happen smoothly.

**Comment by LeBenLeBen** [comment]
@elevatebart Thank you for fixing and releasing so quickly! 🙇
