### ISSUE TITLE
Vue 3 scoped styles do not work on preview

### ISSUE THREAD

**Issue by ardier16** [vue-styleguidist/vue-live#63]
### Description
When passing `code` prop as SFC with scoped styles like this:
```html
<template>
  <p class="test">
    Test
  </p>
</template>

<style>
  .test {
    color: red;
  }
</style>
```
vue-live preview does not apply component styles

It's because component options in vue 3 runtime core accepts `__scopeId` prop ([ref](https://github.com/vuejs/vue-next/blob/4549e65baea54bfd10116241a6a5eba91ec3f632/packages/runtime-core/src/component.ts#L87)), instead of `_scopeId` like in vue 2 ([ref](https://github.com/vuejs/vue/blob/0603ff695d2f41286239298210113cbe2b209e28/flow/options.js#L81)).

If I use `__scopeId` instead of `_scopeId` on this line everything works fine.
https://github.com/vue-styleguidist/vue-live/blob/1a585e9e63b00b98118c193320c3edcf0f98c4f0/src/Preview.vue#L186

I think it should support both `_scopeId` and `__scopeId` for both vue 2 & vue 3 compability.

### Reproduction link
https://codesandbox.io/s/cool-chaum-elh5i

**Comment by ardier16** [comment]
@elevatebart could you please release a new alpha version with the fix?

**Comment by elevatebart** [comment]
@ardier16 I have a hard time figuring out why travis is not running the build.
I checked all that I know.
I will investigate more. Any info would be welcome.

Long story short the version should have been delivered via semantic release automagically. But travis did not run...
