### ISSUE TITLE
[Vue 3] Listeners cause template parse exceptions

### ISSUE THREAD

**Issue by lzurbriggen** [vue-styleguidist/vue-live#65]
## Problem

Adding any listener to `code` leads to errors, e.g:
```vue
<VueLive :code="`<button @click='(event) => myFunc(event)'>click me</button>`"></VueLive>
```
causes:
```
Cannot parse template expression: "(event) => myFunc(event)"

Variable "event" is not defined.
```

The same issue with:
```vue
<VueLive :code="`<button @click='myFunc($event)'>click me</button>`"></VueLive>
```
```
Cannot parse template expression: "myFunc($event)"

Variable "$event" is not defined.
```

The listeners work fine in the application and also don't cause type errors.

## Environment
- `vue-live@2.0.0-alpha.6`
- `vitepress@0.13.2`

**Comment by elevatebart** [comment]
indeed I need to be a little more clever about what I accept as undefined variable: anything starting with a `$` should be OK and of course if the var is created in a function it should be OK too.

I will fix.

**Comment by elevatebart** [comment]
https://github.com/vue-styleguidist/vue-live/commit/536a4a8e91ef50c49a8e3c7b676944b32011d087

**Comment by elevatebart** [comment]
vue-live@2.0.0-alpha.7
