### ISSUE TITLE
Transforming async functions is not implemented. Use `transforms: { asyncAwait: false }` to skip transformation and disable this error.

### ISSUE THREAD

**Issue by enodr** [vue-styleguidist/vue-live#68]
Hi,

My template (SFC) has async functions but I get this error:

`Transforming async functions is not implemented. Use `transforms: { asyncAwait: false }` to skip transformation and disable this error. `

There seems to be a fix here https://github.com/vue-styleguidist/vue-styleguidist/issues/741 but I am confused as how I could force vue-live to use a custom styleguide.config.js config file or pass the option ?

**Comment by enodr** [comment]
Also see regarding Buble: https://github.com/facebook/docusaurus/pull/3954

**Comment by enodr** [comment]
Ok found out the solution which is super simple: we just need to pass the corresponding buble config in Preview.vue:

```
       const renderedComponent = compileScript(
          code,
          this.jsx
            ? { jsx: "__pragma__(h)", objectAssign: "__concatenate__", transforms: {asyncAwait: false}}
            : {transforms: {asyncAwait: false}}
        );
```

**Comment by elevatebart** [comment]
THank you @enodr great research
Would you make a quick PR?

**Comment by elevatebart** [comment]
it seems to have been fixed...

https://github.com/vue-styleguidist/vue-live/blob/3c35891c367ea873834ec36105e9e2e64f511efd/src/Preview.vue#L137-L146
