### ISSUE TITLE
Vue SFC render error: Unterminated string constant

### ISSUE THREAD

**Issue by cong-min** [vue-styleguidist/vue-live#74]
http://vue-live.surge.sh/
When I modify the data `msg: "//vuejs.org"` in the sfc example, I will got a error: `Unterminated string constant (12:11)`

I think this is a bug, the complete code is:
```vue
<template>
  <div class="hello">
    <h1>Colored Text</h1>
    <button>{{ msg }}</button>
  </div>
</template>

<script>
export default {
  data() {
    return {
      msg: "//vuejs.org"
    };
  }
};
</script>

<style>
.hello {
  text-align: center;
  color: #900;
}
</style>
```

**Comment by elevatebart** [comment]
That is indeed a problem. 
This component relies on buble a superlight compiler that is not anymore maintained. 
I am currently working on adapting `esbuild` or `swc` to do the same work (and add typescript compatibility).

If this is an urgent issue for you, please make a PR to the [vue-stuleguidist repo](https://github.com/vue-styleguidist/vue-styleguidist)
