### ISSUE TITLE
v2: Component without a single root node trigger warnings

### ISSUE THREAD

**Issue by LeBenLeBen** [vue-styleguidist/vue-live#76]
If you try to render a component in vue-live that doesn’t hold a single root element, for example:

```vue
<div>A</div>
<div>B</div>
```

It will trigger the following warnings:

> [Vue warn]: Extraneous non-props attributes (id) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
> [Vue warn]: Extraneous non-emits event listeners (detectLanguage, error, success) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.

**Comment by elevatebart** [comment]
Oh !!! good point and probably easy fix. I will get on it this week end if I can.
