### ISSUE TITLE
Any updates on vue 3 with vite?

### ISSUE THREAD

**Issue by jannikbuscha** [vue-styleguidist/vue-live#82]
hey, was wondering if there might be any updates on the integration in vue 3 with vite.

**Comment by elevatebart** [comment]
Yes working in it as we speak. 
More news tonight.

**Comment by jannikbuscha** [comment]
> Yes working in it as we speak. More news tonight.

What exactly are you working on? got it running now using your [repo](https://github.com/vue-styleguidist/vue-live/issues/82#issuecomment-1053718311), but have read that there are apparently still build problems. 

Is there also a way to disable the editor, because I plan to use it only to render my code directly from my markdown.

**Comment by elevatebart** [comment]
Works now !!!

https://github.com/elevatebart/vite-vue-live

**Comment by elevatebart** [comment]
If your idea is to render vue components in a md file, you might be better off directly with vitepress.

**Comment by jannikbuscha** [comment]
> 
vitepress is an option in itself but the custom layout options are not so good. Seems like they are solving this better now with
https://github.com/vuepress/vuepress-next
