### ISSUE TITLE
Add support for script setup

### ISSUE THREAD

**Issue by elevatebart** [vue-styleguidist/vue-live#94]
For now, only the options api and the normal composition api work. 

Let's investigate how to compile script setup.

**Comment by susnux** [comment]
This should be automatically be done if using `@vue/compiler-sfc` as it takes the whole SFC: https://github.com/vuejs/core/blob/fe77e2bddaa5930ad37a43fe8e6254ddb0f9c2d7/packages/compiler-sfc/src/compileScript.ts#L142
