### ISSUE TITLE
How to handle imported components

### ISSUE THREAD

**Issue by susnux** [vue-styleguidist/vue-live#96]
My example code I want to preview looks like this:

```vue
<template>
    <some-component>
      <template #icon>
        <Delete />
      </template>
    </some-component>
</template>
<script>
import Delete from 'vue-material-design-icons/Delete.vue'

export default {
  components: {
    Delete
  },
}
</script>
```

And the vue-live part looking like this:

```vue
<vue-live
    :code="codeFromAbove"
    :requires="{'vue-material-design-icons/Delete.vue': import('vue-material-design-icons/Delete.vue')}"
/>
```

But the Delete icon is not shown and following vue error is printed:
> [Vue warn]: Failed to resolve component: Delete
> If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 

---

#### Using await as import return a Promise with the module:
```vue
<vue-live
    :code="codeFromAbove"
    :requires="{'vue-material-design-icons/Delete.vue': (await import('vue-material-design-icons/Delete.vue')).default}"
/>
```
Error:
> [plugin:vite:vue] Error parsing JavaScript expression: 'await' is only allowed within async functions and at the top levels of modules. (1:39)

#### Using `require` instead of `import`
```vue
<vue-live
    :code="codeFromAbove"
    :requires="{'vue-material-design-icons/Delete.vue': require('vue-material-design-icons/Delete.vue')}"
/>
```

Error:
> Uncaught (in promise) ReferenceError: require is not defined

**Comment by elevatebart** [comment]
in what context are you using vue-live ?
vitepress? vuepress? Nuxt? vue-cli ?

The "imports" should be done outside of the template so they can be resolved at build time instead of on the browser.
So depending on the context, these will be done in one or another place.

I hope this helps a bit.

**Comment by susnux** [comment]
> in what context are you using vue-live ? vitepress? vuepress? Nuxt? vue-cli ?

I am using `docgen-cli` + `vitepress`
It is basically based on the example in the vue-styleguideist repository.

**Comment by susnux** [comment]
It works when using a wrapper component that ensures all imports are resolved.

So `vue-live` is only working with synchronous `require` and not ES6 imports?

```js
import { h, onMounted, ref, defineComponent } from "vue"
import { VueLive } from "vue-live";
import layout from "./vue-live-layout.vue";

export default defineComponent({
	setup(_, { attrs }) {
		const ready = ref(false)
		const props = {...attrs}
		onMounted(async () => {
			if ("requires" in props) {
				props.requires = {}
				await Promise.allSettled(Object.keys(attrs.requires).map(async (key) => {
					props.requires[key] = (await attrs.requires[key]).default
				}))
			}
			ready.value = true
		})
		// return the render function
		return () => ready.value ? h(VueLive, { ...props, layout }) : h('div', 'loading...')
	}
})
```

Of cause this only works when importing the *default* export and not any named export.
